name: CI Build-Test-Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Bun (for "bun i" in build script)
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Build (ncc)
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            dist/**
            licenses.txt
          if-no-files-found: error

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./build_artifact

      - name: Run tests
        run: npm test

  release:
    name: Release (dev)
    runs-on: ubuntu-latest
    needs: test
    environment: dev
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./dist

      - name: Create GitHub Release (attach artifact)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dev-${{ github.run_number }}
          name: "Dev Release #${{ github.run_number }}"
          body: "自動產生的發行版本（測試通過後釋出）"
          files: |
            ./dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
