name: CI Build-Test-Release
on:
  push:
    branches: [ master ]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test -- --coverage 
      - name: Publish Release
        if: ${{ success() }}
        uses: softprops/action-gh-release@v1
        with:
            tag_name: ${{ github.run_number }}
            name: "Release ${{ github.run_number }}"
            body: "自動產生的發行版本"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

